var hierarchy =
[
    [ "AlertManager", "d0/d5b/classAlertManager.html", null ],
    [ "AnyPointM2_params", "d6/d36/structAnyPointM2__params.html", null ],
    [ "AnyPointM_params", "d1/d9d/structAnyPointM__params.html", null ],
    [ "AppCameraParams", "d6/d47/structAppCameraParams.html", null ],
    [ "BaseController", "d3/d75/classBaseController.html", [
      [ "ConfigurationController", "d3/d3d/classConfigurationController.html", null ],
      [ "LiveViewController", "d6/d8a/classLiveViewController.html", null ],
      [ "PlaybackController", "d0/d22/classPlaybackController.html", null ],
      [ "SettingController", "d9/ddd/classSettingController.html", null ]
    ] ],
    [ "BaseModel< RecordType >", "d8/d7f/classBaseModel.html", null ],
    [ "BaseModel< FrameRecord >", "d8/d7f/classBaseModel.html", [
      [ "FrameModel", "dd/d08/classFrameModel.html", null ]
    ] ],
    [ "BaseModel< FunctionRecord >", "d8/d7f/classBaseModel.html", [
      [ "FunctionModel", "d2/dd2/classFunctionModel.html", null ]
    ] ],
    [ "BaseModel< RegionRecord >", "d8/d7f/classBaseModel.html", [
      [ "RegionModel", "de/d06/classRegionModel.html", null ]
    ] ],
    [ "BaseModel< SourceRecord >", "d8/d7f/classBaseModel.html", [
      [ "SourceModel", "d5/d04/classSourceModel.html", null ]
    ] ],
    [ "BaseView", "dd/d94/classBaseView.html", [
      [ "App", "dd/d64/classApp.html", null ],
      [ "ConfigurationView", "d1/db4/classConfigurationView.html", null ],
      [ "LiveViewView", "d0/d13/classLiveViewView.html", null ],
      [ "PlaybackView", "d2/d2b/classPlaybackView.html", null ],
      [ "SettingView", "dc/d7c/classSettingView.html", null ]
    ] ],
    [ "BorderStyleData", "d2/d8d/structBorderStyleData.html", null ],
    [ "VRUDetector::BsisZonedRisk", "de/dfc/structVRUDetector_1_1BsisZonedRisk.html", null ],
    [ "ButtonImageData", "dd/d1e/structButtonImageData.html", null ],
    [ "VideoProcessor::CacheKey", "de/d75/structVideoProcessor_1_1CacheKey.html", null ],
    [ "CameraManager", "d8/dbf/classCameraManager.html", null ],
    [ "CameraParams", "d4/daf/structCameraParams.html", null ],
    [ "CameraProcessor", "d7/d7c/classCameraProcessor.html", null ],
    [ "Beeper::Config", "d0/dc8/structBeeper_1_1Config.html", null ],
    [ "Detection", "d4/d3a/structDetection.html", null ],
    [ "VRUDetector::DetectionPack", "dc/dac/structVRUDetector_1_1DetectionPack.html", null ],
    [ "DetectionResult", "d8/d80/structDetectionResult.html", null ],
    [ "VideoProcessor::DetectionResult", "d0/d01/structVideoProcessor_1_1DetectionResult.html", null ],
    [ "ConfigurationView::DragPosition", "d8/d6f/structConfigurationView_1_1DragPosition.html", null ],
    [ "VRUDetector::EditState", "d5/d00/structVRUDetector_1_1EditState.html", null ],
    [ "FrameRecord", "db/da9/structFrameRecord.html", null ],
    [ "FrameProcessor::FunctionProcess", "db/dec/structFrameProcessor_1_1FunctionProcess.html", null ],
    [ "FunctionRecord", "df/df2/structFunctionRecord.html", null ],
    [ "IdleData", "d1/d50/structIdleData.html", null ],
    [ "moildev::IMoildevBackend", "de/d31/classmoildev_1_1IMoildevBackend.html", null ],
    [ "IMoildevPlugin", "da/d65/structIMoildevPlugin.html", null ],
    [ "VideoProcessor::KeyHash", "dd/d0e/structVideoProcessor_1_1KeyHash.html", null ],
    [ "LiveViewView::MediaDialogResult", "d1/de7/structLiveViewView_1_1MediaDialogResult.html", null ],
    [ "Mediator", "df/dd5/classMediator.html", null ],
    [ "MessageDialog", "de/d7b/classMessageDialog.html", null ],
    [ "moildev::cpu::Moildev", "d4/d96/classmoildev_1_1cpu_1_1Moildev.html", null ],
    [ "moildev::Moildev", "d5/dda/classmoildev_1_1Moildev.html", null ],
    [ "moildev::ocl::Moildev", "db/d92/classmoildev_1_1ocl_1_1Moildev.html", null ],
    [ "MoildevApplicator", "d7/d8b/classMoildevApplicator.html", null ],
    [ "VRUDetector::MoisZonedRisk", "d9/df8/structVRUDetector_1_1MoisZonedRisk.html", null ],
    [ "VRUDetector::MoisZonedRisk3", "da/d41/structVRUDetector_1_1MoisZonedRisk3.html", null ],
    [ "ResourceMonitor::Monitor", "d7/d1a/classResourceMonitor_1_1Monitor.html", null ],
    [ "PanoramaCar_params", "da/d99/structPanoramaCar__params.html", null ],
    [ "PanoramaCar_precalc_alpha", "df/de3/structPanoramaCar__precalc__alpha.html", null ],
    [ "PanoramaCar_precalc_beta", "d5/d1a/structPanoramaCar__precalc__beta.html", null ],
    [ "PanoramaRev_params", "df/df8/structPanoramaRev__params.html", null ],
    [ "PanoramaTube_params", "d6/d54/structPanoramaTube__params.html", null ],
    [ "ResourceMonitor::ProcessMetrics", "d7/da5/structResourceMonitor_1_1ProcessMetrics.html", null ],
    [ "RecordProcessor::RecordStats", "dd/d95/structRecordProcessor_1_1RecordStats.html", null ],
    [ "RegionRecord", "d7/d65/structRegionRecord.html", null ],
    [ "ResolutionProcessor::Resolutions", "d1/d20/structResolutionProcessor_1_1Resolutions.html", null ],
    [ "VRUDetector::ROIBoxes", "d9/d4d/structVRUDetector_1_1ROIBoxes.html", null ],
    [ "VideoProcessor::Seed", "d2/d53/structVideoProcessor_1_1Seed.html", null ],
    [ "SourceRecord", "dc/d4a/structSourceRecord.html", null ],
    [ "ThreadPool", "dc/de7/classThreadPool.html", null ],
    [ "Constants::ViewParams", "d7/dfe/structConstants_1_1ViewParams.html", null ],
    [ "VRUDetector::VRUSnapshot", "de/d5c/structVRUDetector_1_1VRUSnapshot.html", null ],
    [ "YoloV3Detector", "d4/d57/classYoloV3Detector.html", null ],
    [ "YoloV8Detector", "da/dbb/classYoloV8Detector.html", null ],
    [ "ZonePolicy", "d7/d1f/structZonePolicy.html", null ],
    [ "VRUDetector::ZoneRisk", "d8/d26/structVRUDetector_1_1ZoneRisk.html", null ],
    [ "VRUDetector::ZoneRisk3", "d7/d57/structVRUDetector_1_1ZoneRisk3.html", null ],
    [ "VRUDetector::ZoningConfig", "d6/dcf/structVRUDetector_1_1ZoningConfig.html", null ]
];